server:
  port: 8543

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

logging:
  level:
    com:
      netflix:
        eureka: WARN
        discovery: WARN
    org:
      springframework:
        cloud: WARN