FROM maven:3.9-eclipse-temurin-17 AS builder

WORKDIR /glossary-service

COPY glossary-service/pom.xml .

RUN mvn dependency:go-offline -B

COPY glossary-service/src ./src

RUN mvn clean package -DskipTests

FROM tomcat:10.1-jdk17

COPY --from=builder /glossary-service/target/glossary.war /usr/local/tomcat/webapps/glossary.war