FROM maven:3.9-eclipse-temurin-17 AS builder

WORKDIR /request-service

COPY request-service/pom.xml .
COPY request-service/src ./src

RUN mvn clean package -DskipTests

FROM tomcat:10.1-jdk17

COPY --from=builder /request-service/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]