services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PGPORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  glossary-service:
    build:
      context: .
      dockerfile: Dockerfile.glossary
    container_name: glossary-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  request-service:
    hostname: request-service
    build:
      context: .
      dockerfile: Dockerfile.request
    container_name: request-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy


  mission-service:
    hostname: mission-service
    build:
      context: .
      dockerfile: Dockerfile.mission
    container_name: mission-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  registry:
    hostname: registry
    build:
      context: .
      dockerfile: Dockerfile.registry
    container_name: service-registry
    ports:
      - "8761:8761"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy