services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"

#  glossary-service:
#    hostname: glossary-service
#    build:
#      context: .
#      dockerfile: Dockerfile.glossary
#    container_name: glossary-service
#    env_file:
#      - .env
#    environment:
#      SERVER_SERVLET_CONTEXT_PATH: /glossary-service
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#  request-service:
#    hostname: request-service
#    build:
#      context: .
#      dockerfile: Dockerfile.request
#    container_name: request-service
#    env_file:
#      - .env
#    environment:
#      SERVER_SERVLET_CONTEXT_PATH: /request-service
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#
#  mission-service:
#    hostname: mission-service
#    build:
#      context: .
#      dockerfile: Dockerfile.mission
#    container_name: mission-service
#    env_file:
#      - .env
#    environment:
#      SERVER_SERVLET_CONTEXT_PATH: /mission-service
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#  registry:
#    hostname: registry
#    build:
#      context: .
#      dockerfile: Dockerfile.registry
#    container_name: service-registry
#    ports:
#      - "8761:8761"
#    env_file:
#      - .env
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#  delivery-point-service:
#    hostname: delivery-point-service
#    build:
#      context: .
#      dockerfile: Dockerfile.delivery-point
#    container_name: delivery-point-service
#    env_file:
#      - .env
#    environment:
#      SERVER_SERVLET_CONTEXT_PATH: /delivery-point-service
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#  employee-service:
#    hostname: employee-service
#    build:
#      context: .
#      dockerfile: Dockerfile.employee
#    container_name: employee-service
#    env_file:
#      - .env
#    environment:
#      SERVER_SERVLET_CONTEXT_PATH: /employee-service
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#  gateway-service:
#    hostname: gateway-service
#    build:
#      context: .
#      dockerfile: Dockerfile.gateway
#    container_name: gateway-service
#    ports:
#      - "8080:8079"
#    env_file:
#      - .env
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#  logistic-service:
#    hostname: logistic-service
#    build:
#      context: .
#      dockerfile: Dockerfile.logistic
#    container_name: logistic-service
#    env_file:
#      - .env
#    environment:
#      SERVER_SERVLET_CONTEXT_PATH: /logistic-service
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#  station-service:
#    hostname: station-service
#    build:
#      context: .
#      dockerfile: Dockerfile.station
#    container_name: station-service
#    env_file:
#      - .env
#    environment:
#      SERVER_SERVLET_CONTEXT_PATH: /station-service
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#  store-service:
#    hostname: store-service
#    build:
#      context: .
#      dockerfile: Dockerfile.store
#    container_name: store-service
#    env_file:
#      - .env
#    environment:
#      SERVER_SERVLET_CONTEXT_PATH: /store-service
#    depends_on:
#      postgres:
#        condition: service_healthy
#
##  team-service:
##    hostname: team-service
##    build:
##      context: .
##      dockerfile: Dockerfile.team
##    container_name: team-service
##    env_file:
##      - .env
##    environment:
##      SERVER_SERVLET_CONTEXT_PATH: /team-service
##    depends_on:
##      postgres:
##        condition: service_healthy
