spring:
  application:
    name: "ecosystem-service"
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${PGPORT}/db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true