spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: "ecosystem-service"
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${PGPORT}/db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        bytecode:
          provider: none
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

server:
  port: ${SERVER_PORT}
logging:
  level:
    com:
      netflix:
        eureka: ERROR
        discovery: ERROR
    org:
      springframework:
        web: DEBUG