spring:
  application:
    name: "gateway"

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        loggerLevel: full

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8543/eureka}
  instance:
    prefer-ip-address: true

server:
  port: ${SERVER_PORT:6789}
logging:
  level:
    org:
      springframework:
        web: DEBUG
