spring:
  application:
    name: "gateway"

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        loggerLevel: full

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:1390/eureka}
  instance:
    prefer-ip-address: true

server:
  port: ${SERVER_PORT:1381}
  tomcat:
    threads:
      max: 5
logging:
  level:
    com:
      netflix:
        eureka: ERROR
        discovery: ERROR
    org:
      springframework:
        web: DEBUG
